<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                "first_name" => "Limberth",
                "last_name" => "Alarcón  Avendaño",
                "ci" => "2862429 Cbba",
                "registration_code" => "03-003",
                "password" => "03-003",
                "email" => "lalarcon@ctb.com.bo",
                "address" => "Calle Rosas s/n",
                "mobile_number" => "71714935",
                "phone_number" => "",
                "college_affiliation_date" => "1997-05-04"
            ],
            [
                "first_name" => "René  Max",
                "last_name" => "Luna  Chuquimia",
                "ci" => "2553140 L.P.",
                "registration_code" => "03-004",
                "password" => "03-004",
                "email" => "topo_luna@hotmail.com",
                "address" => "c/ Moliere N° 110",
                "mobile_number" => "72734491",
                "phone_number" => "4582436",
                "college_affiliation_date" => "1997-05-04"
            ],
            [
                "first_name" => "John  William",
                "last_name" => "Chavarría  Álvarez",
                "ci" => "2348491 LP.",
                "registration_code" => "03-005",
                "password" => "03-005",
                "email" => "chava73@hotmail.com",
                "address" => "c/ Pojo N° 286",
                "mobile_number" => "72295521",
                "phone_number" => "4553643",
                "college_affiliation_date" => "1997-05-04"
            ],
            [
                "first_name" => "Edgar Gonzalo",
                "last_name" => "Figueredo  Salcedo",
                "ci" => "072294 L.P.",
                "registration_code" => "03-007",
                "password" => "03-007",
                "email" => "efigueredo@ctb.com.bo",
                "address" => "c/ Leon Tolstoy N° 123",
                "mobile_number" => "71766451",
                "phone_number" => "4291845",
                "college_affiliation_date" => "1997-05-04"
            ],
            [
                "first_name" => "Luis  Roberto",
                "last_name" => "Navarro  Loayza",
                "ci" => "2334421 L.P.",
                "registration_code" => "03-008",
                "password" => "03-008",
                "email" => "navarro.docente2020@gmail.com",
                "address" => "Calle Montenegro N° 400",
                "mobile_number" => "71754211",
                "phone_number" => "4474006",
                "college_affiliation_date" => "1997-05-04"
            ],
            [
                "first_name" => "Elio  Natalio",
                "last_name" => "León  Roque",
                "ci" => "4314445 L.P.",
                "registration_code" => "03-013",
                "password" => "03-013",
                "email" => "elioleonroque@gmail.com",
                "address" => "",
                "mobile_number" => "71438067",
                "phone_number" => "4660637",
                "college_affiliation_date" => "2010-05-30"
            ],
            [
                "first_name" => "Emilio",
                "last_name" => "Choque  Mejía",
                "ci" => "2727924 Or.",
                "registration_code" => "03-016",
                "password" => "03-016",
                "email" => "echoque@ctb.com.bo",
                "address" => "c/Antenor de la Via s/n",
                "mobile_number" => "74342887",
                "phone_number" => "4022244",
                "college_affiliation_date" => "2010-04-26"
            ],
            [
                "first_name" => "Rioni",
                "last_name" => "Unzueta  Bustamante",
                "ci" => "3620685 Cbba.",
                "registration_code" => "03-019",
                "password" => "03-019",
                "email" => "runzueta@ctb.com.bo",
                "address" => "",
                "mobile_number" => "70798676",
                "phone_number" => "4766213",
                "college_affiliation_date" => "2010-07-26"
            ],
            [
                "first_name" => "Freddy  Leonardo",
                "last_name" => "Torrez  Quisbet",
                "ci" => "2291980 L.P.",
                "registration_code" => "03-027",
                "password" => "03-027",
                "email" => "ftorrez@ctb.com.bo",
                "address" => "c/ Ivan Bluske N° 220",
                "mobile_number" => "71745816",
                "phone_number" => "7020162",
                "college_affiliation_date" => "2010-09-06"
            ],
            [
                "first_name" => "Reynel  Cesar",
                "last_name" => "Aguilar  Conde",
                "ci" => "2709227 L.P.",
                "registration_code" => "03-032",
                "password" => "03-032",
                "email" => "raguilar@ctb.com.bo",
                "address" => "",
                "mobile_number" => "77420034",
                "phone_number" => "4431816",
                "college_affiliation_date" => "2011-02-10"
            ],
            [
                "first_name" => "Edzon",
                "last_name" => "Sánchez  Revollo",
                "ci" => "5274323 Cbba.",
                "registration_code" => "03-035",
                "password" => "03-035",
                "email" => "edzonsr1@gmail.com",
                "address" => "c/ Martin Cardenas s/n",
                "mobile_number" => "72277751",
                "phone_number" => "4457928",
                "college_affiliation_date" => "2011-05-14"
            ],
            [
                "first_name" => "Juanito",
                "last_name" => "Gutiérrez  Rojas",
                "ci" => "5183783 Cbba.",
                "registration_code" => "03-039",
                "password" => "03-039",
                "email" => "jgutierrez@ctb.com.bo",
                "address" => "",
                "mobile_number" => "74360025",
                "phone_number" => "",
                "college_affiliation_date" => "2011-07-06"
            ],
            [
                "first_name" => "Ramiro",
                "last_name" => "Fuentes",
                "ci" => "5920189 Cbba.",
                "registration_code" => "03-057",
                "password" => "03-057",
                "email" => "rfuentes@ctb.com.bo",
                "address" => "",
                "mobile_number" => "76481090",
                "phone_number" => "4730132",
                "college_affiliation_date" => "2012-03-21"
            ],
            [
                "first_name" => "Juan",
                "last_name" => "Mamani  Solís",
                "ci" => "6459044 Cbba.",
                "registration_code" => "03-070",
                "password" => "03-070",
                "email" => "jmamani@ctb.com.bo",
                "address" => "",
                "mobile_number" => "76901927",
                "phone_number" => "",
                "college_affiliation_date" => "2012-07-06"
            ],
            [
                "first_name" => "Reina  Angélica",
                "last_name" => "Escobar  Cayo",
                "ci" => "4518961 Cbba.",
                "registration_code" => "03-083",
                "password" => "03-083",
                "email" => "rescobar@ctb.com.bo",
                "address" => "",
                "mobile_number" => "72247242",
                "phone_number" => "",
                "college_affiliation_date" => "2013-09-01"
            ],
            [
                "first_name" => "Luis  Adalid",
                "last_name" => "Orellana  Mamani",
                "ci" => "3777919 Cbba.",
                "registration_code" => "03-089",
                "password" => "03-089",
                "email" => "gt.laom70@gmail.com",
                "address" => "",
                "mobile_number" => "67409551",
                "phone_number" => "4312303",
                "college_affiliation_date" => "2014-05-28"
            ],
            [
                "first_name" => "Máximo",
                "last_name" => "Calizaya  Cabrera",
                "ci" => "5240473 Cbba.",
                "registration_code" => "03-093",
                "password" => "03-093",
                "email" => "mcalizaya@ctb.com.bo",
                "address" => "",
                "mobile_number" => "68515407",
                "phone_number" => "4242408",
                "college_affiliation_date" => "2015-04-01"
            ],
            [
                "first_name" => "Dennys",
                "last_name" => "Antezana  Mamani",
                "ci" => "5317396 Cbba.",
                "registration_code" => "03-094",
                "password" => "03-094",
                "email" => "dantezana@ctb.com.bo",
                "address" => "",
                "mobile_number" => "76482585",
                "phone_number" => "4409192",
                "college_affiliation_date" => "2015-04-01"
            ],
            [
                "first_name" => "Juan  Rudy",
                "last_name" => "Uño  Rodriguez",
                "ci" => "9349772 Cbba.",
                "registration_code" => "03-102",
                "password" => "03-102",
                "email" => "juno@ctb.com.bo",
                "address" => "",
                "mobile_number" => "77995530",
                "phone_number" => "",
                "college_affiliation_date" => "2015-12-03"
            ],
            [
                "first_name" => "Ernesto",
                "last_name" => "Yucra  Coca",
                "ci" => "5901233 Cbba",
                "registration_code" => "03-103",
                "password" => "03-103",
                "email" => "eyucra@ctb.com.bo",
                "address" => "",
                "mobile_number" => "79394521",
                "phone_number" => "4511646",
                "college_affiliation_date" => "2016-01-28"
            ],
            [
                "first_name" => "Alexis  Rene",
                "last_name" => "Apaza  Huanto",
                "ci" => "7868705 Cbba.",
                "registration_code" => "03-107",
                "password" => "03-107",
                "email" => "aapaza@ctb.com.bo",
                "address" => "",
                "mobile_number" => "79751027",
                "phone_number" => "4746751",
                "college_affiliation_date" => "2016-05-23"
            ],
            [
                "first_name" => "Claudia",
                "last_name" => "Villarroel  Carballo",
                "ci" => "7982576 Cbba.-",
                "registration_code" => "03-109",
                "password" => "03-109",
                "email" => "cvillarroelcarballo@gmail.com",
                "address" => "",
                "mobile_number" => "68534145",
                "phone_number" => "",
                "college_affiliation_date" => "2015-02-26"
            ],
            [
                "first_name" => "Raul",
                "last_name" => "Lopez  Torrico",
                "ci" => "",
                "registration_code" => "03-113",
                "password" => "03-113",
                "email" => "rlopez@ctb.com.bo",
                "address" => "",
                "mobile_number" => "72297834",
                "phone_number" => "",
                "college_affiliation_date" => "2017-04-25"
            ],
            [
                "first_name" => "Vladimir  Denis",
                "last_name" => "Martinelly  Zeballos",
                "ci" => "",
                "registration_code" => "03-121",
                "password" => "03-121",
                "email" => "vmartinelly@ctb.com.bo",
                "address" => "",
                "mobile_number" => "72796243",
                "phone_number" => "",
                "college_affiliation_date" => "2017-11-12"
            ],
            [
                "first_name" => "Jorge  F.",
                "last_name" => "Rojas  Ramallo",
                "ci" => "",
                "registration_code" => "03-125",
                "password" => "03-125",
                "email" => "Jorge.f.rojas.r@gmail.com",
                "address" => "",
                "mobile_number" => "",
                "phone_number" => "4409144",
                "college_affiliation_date" => "2010-02-05"
            ],
            [
                "first_name" => "Deymar",
                "last_name" => "Garcia  Orellana",
                "ci" => "",
                "registration_code" => "03-129",
                "password" => "03-129",
                "email" => "garciaorellanadeymar69@gmail.com",
                "address" => "",
                "mobile_number" => "77940628",
                "phone_number" => "",
                "college_affiliation_date" => "2018-06-06"
            ],
            [
                "first_name" => "Edwin",
                "last_name" => "Peña  Alvarado",
                "ci" => "",
                "registration_code" => "03-131",
                "password" => "03-131",
                "email" => "top95albarado@gmail.com",
                "address" => "",
                "mobile_number" => "79336694",
                "phone_number" => "",
                "college_affiliation_date" => "2018-11-26"
            ],
            [
                "first_name" => "Carlos",
                "last_name" => "Caceres  Claros",
                "ci" => "7955607 cbba.",
                "registration_code" => "03-133",
                "password" => "03-133",
                "email" => "caceresclaros@gmail.com",
                "address" => "",
                "mobile_number" => "67538441",
                "phone_number" => "",
                "college_affiliation_date" => "2019-01-24"
            ],
            [
                "first_name" => "Christian",
                "last_name" => "Flores  Rodriguez",
                "ci" => "",
                "registration_code" => "03-135",
                "password" => "03-135",
                "email" => "cflores@ctb.com.bo",
                "address" => "",
                "mobile_number" => "68479192",
                "phone_number" => "",
                "college_affiliation_date" => "NULL"
            ],
            [
                "first_name" => "Miguel  A.",
                "last_name" => "Condori  Ramallo",
                "ci" => "7934184 Cbba",
                "registration_code" => "03-136",
                "password" => "03-136",
                "email" => "angel10.10mr@gmail.com",
                "address" => "Pacata Alta N° 10",
                "mobile_number" => "60763310",
                "phone_number" => "",
                "college_affiliation_date" => "2020-06-26"
            ],
            [
                "first_name" => "Edgar",
                "last_name" => "Flores  Cruz",
                "ci" => "7045410 L.P.",
                "registration_code" => "03-137",
                "password" => "03-137",
                "email" => "eflores@ctb.com.bo",
                "address" => "",
                "mobile_number" => "67575499",
                "phone_number" => "",
                "college_affiliation_date" => "2019-02-16"
            ],
            [
                "first_name" => "Bernardo",
                "last_name" => "Ayala  Rocha",
                "ci" => "13896613 Cbba",
                "registration_code" => "03-138",
                "password" => "03-138",
                "email" => "ayalaalbabernardo@gmail.com",
                "address" => "Av. Suarez miranda N° 927",
                "mobile_number" => "67407614",
                "phone_number" => "",
                "college_affiliation_date" => "2019-05-24"
            ],
            [
                "first_name" => "Wilber",
                "last_name" => "Gomez  Quiroz",
                "ci" => "8681028 Cbba",
                "registration_code" => "03-139",
                "password" => "03-139",
                "email" => "wil.g.quiroz@gmail.com",
                "address" => "C/ Ayacucho N° 343-Sacaba",
                "mobile_number" => "67551521",
                "phone_number" => "",
                "college_affiliation_date" => "2019-05-31"
            ],
            [
                "first_name" => "Alex",
                "last_name" => "Alcamamani  Porco",
                "ci" => "8660647 Cbba",
                "registration_code" => "03-141",
                "password" => "03-141",
                "email" => "alex.alpo.43@gmail.com",
                "address" => "C/ Innominada",
                "mobile_number" => "76957646",
                "phone_number" => "",
                "college_affiliation_date" => "2019-06-17"
            ],
            [
                "first_name" => "Celestino",
                "last_name" => "Juchasara  Javier",
                "ci" => "877687 Cbba",
                "registration_code" => "03-142",
                "password" => "03-142",
                "email" => "cjuchasara@ctb.com.bo",
                "address" => "Pucara Grande",
                "mobile_number" => "77429309",
                "phone_number" => "",
                "college_affiliation_date" => "2020-07-26"
            ],
            [
                "first_name" => "Benjamin  Amadeo",
                "last_name" => "Bustos  Flores",
                "ci" => "8718639 Cbba",
                "registration_code" => "03-143",
                "password" => "03-143",
                "email" => "bempo777@gmail.com",
                "address" => "Villa San Rafael- Chapare",
                "mobile_number" => "79790014",
                "phone_number" => "",
                "college_affiliation_date" => "2019-08-09"
            ],
            [
                "first_name" => "Carla",
                "last_name" => "Marcos  Lopez",
                "ci" => "7997791 Cbba",
                "registration_code" => "03-144",
                "password" => "03-144",
                "email" => "carly31marcus@gmail.com",
                "address" => "Av Petrolera 3y 1/2",
                "mobile_number" => "76460154",
                "phone_number" => "",
                "college_affiliation_date" => "2019-08-26"
            ],
            [
                "first_name" => "Jose  Jhonny",
                "last_name" => "Quiroz  Sanchez",
                "ci" => "7923599 Cbba",
                "registration_code" => "03-145",
                "password" => "03-145",
                "email" => "josejhon399@gmail.com",
                "address" => "C/ Ayacucho N° 343- Sacaba",
                "mobile_number" => "67551793",
                "phone_number" => "",
                "college_affiliation_date" => "2019-10-18"
            ],
            [
                "first_name" => "Juan  Pablo",
                "last_name" => "Mariscal  Gabriel",
                "ci" => "6516393 Cbba",
                "registration_code" => "03-147",
                "password" => "03-147",
                "email" => "jmariscal@ctb.com.bo",
                "address" => "Reducto Tiquipaya",
                "mobile_number" => "70344361",
                "phone_number" => "",
                "college_affiliation_date" => "2020-02-05"
            ],
            [
                "first_name" => "Cristobal",
                "last_name" => "Arispe  Vallejos",
                "ci" => "7967458 cbba.",
                "registration_code" => "03-148",
                "password" => "03-148",
                "email" => "cristobalarispe@gmail.com",
                "address" => "C/ Aroma- Sacaba",
                "mobile_number" => "7967458",
                "phone_number" => "",
                "college_affiliation_date" => "2020-07-28"
            ],
            [
                "first_name" => "Nelson  Mamani",
                "last_name" => "Coyo",
                "ci" => "8049173 Cbba",
                "registration_code" => "03-149",
                "password" => "03-149",
                "email" => "nelcoyo123@gmail.com",
                "address" => "Villa 14 Sep-Chapare",
                "mobile_number" => "63961414",
                "phone_number" => "",
                "college_affiliation_date" => "2020-08-19"
            ],
            [
                "first_name" => "Ruben",
                "last_name" => "Guarachi  Aspi",
                "ci" => "4946362 L.P.",
                "registration_code" => "03-150",
                "password" => "03-150",
                "email" => "rubguarachi@gmail.com",
                "address" => "",
                "mobile_number" => "74818650",
                "phone_number" => "",
                "college_affiliation_date" => "2022-10-19"
            ],
            [
                "first_name" => "David",
                "last_name" => "Caceres  Claros",
                "ci" => "8815309 Cbba",
                "registration_code" => "03-152",
                "password" => "03-152",
                "email" => "caceres.dcc33@gmail.com",
                "address" => "Av Martin C.- Chapare",
                "mobile_number" => "67447692",
                "phone_number" => "",
                "college_affiliation_date" => "2020-08-19"
            ],
            [
                "first_name" => "Pedro",
                "last_name" => "Illanes  Laime",
                "ci" => "4469775 Cbba",
                "registration_code" => "03-153",
                "password" => "03-153",
                "email" => "p.illanes200@gmail.com",
                "address" => "Alto Alianza-Punata",
                "mobile_number" => "71430534",
                "phone_number" => "",
                "college_affiliation_date" => "2019-03-04"
            ],
            [
                "first_name" => "Ivan  Natan",
                "last_name" => "Balderrama  Oquendo",
                "ci" => "",
                "registration_code" => "03-154",
                "password" => "03-154",
                "email" => "raudoiwalkalone44@gmail.com",
                "address" => "Blanco G.-Quillacollo",
                "mobile_number" => "70383371",
                "phone_number" => "",
                "college_affiliation_date" => "2020-10-21"
            ],
            [
                "first_name" => "Julian",
                "last_name" => "Aracayo  Valencia",
                "ci" => "",
                "registration_code" => "03-155",
                "password" => "03-155",
                "email" => "jaracayo@ctb.com.bo",
                "address" => "",
                "mobile_number" => "72070054",
                "phone_number" => "",
                "college_affiliation_date" => "2020-11-13"
            ],
            [
                "first_name" => "Lino  Lider",
                "last_name" => "Rivera  Vela",
                "ci" => "8835847 Cbba",
                "registration_code" => "03-156",
                "password" => "03-156",
                "email" => "lider.surveyor@gmail.com",
                "address" => "Centro Glorieta-Sacaba",
                "mobile_number" => "74809557",
                "phone_number" => "",
                "college_affiliation_date" => "2020-12-04"
            ],
            [
                "first_name" => "Roman",
                "last_name" => "Caisina  Millares",
                "ci" => "10516969 Pts.",
                "registration_code" => "03-157",
                "password" => "03-157",
                "email" => "romanmillares@gmail.com",
                "address" => "Av Reducto-Tiquipaya",
                "mobile_number" => "60361498",
                "phone_number" => "",
                "college_affiliation_date" => "2020-12-04"
            ],
            [
                "first_name" => "Benjamin",
                "last_name" => "Merida  Sanchez",
                "ci" => "8716889 Cbba",
                "registration_code" => "03-158",
                "password" => "03-158",
                "email" => "benjamin.mz@gmail.com",
                "address" => "C/ Beni - Sacaba",
                "mobile_number" => "72286342",
                "phone_number" => "",
                "college_affiliation_date" => "2021-01-22"
            ],
            [
                "first_name" => "Neiza",
                "last_name" => "Valdivia  Lopez",
                "ci" => "6524010 Cbba",
                "registration_code" => "03-159",
                "password" => "03-159",
                "email" => "valdivia5pez@gmail.com",
                "address" => "Petrolera 4 y 1/2",
                "mobile_number" => "60723373",
                "phone_number" => "",
                "college_affiliation_date" => "2021-02-05"
            ],
            [
                "first_name" => "Eduardo",
                "last_name" => "Calizaya  Yucra",
                "ci" => "6536239 Cbba",
                "registration_code" => "03-160",
                "password" => "03-160",
                "email" => "edu_calizaya88@hotmail.com",
                "address" => "Av Villazon 7 1/2",
                "mobile_number" => "74362428",
                "phone_number" => "",
                "college_affiliation_date" => "2021-02-05"
            ],
            [
                "first_name" => "Diemar",
                "last_name" => "Flores  Vidal",
                "ci" => "9455370 Cbba",
                "registration_code" => "03-161",
                "password" => "03-161",
                "email" => "Diemar_fv@gmail.com",
                "address" => "tiraque",
                "mobile_number" => "72795134",
                "phone_number" => "",
                "college_affiliation_date" => "2021-02-11"
            ],
            [
                "first_name" => "Reinaldo",
                "last_name" => "Rojas  Rocha",
                "ci" => "4473396 Cbba",
                "registration_code" => "03-164",
                "password" => "03-164",
                "email" => "rojas_35topgraf@hotmail.com",
                "address" => "P matias - Ticti Sud",
                "mobile_number" => "71718577",
                "phone_number" => "",
                "college_affiliation_date" => "2021-03-09"
            ],
            [
                "first_name" => "Adalith",
                "last_name" => "Gonzales  Ramirez",
                "ci" => "7966121 Cbba",
                "registration_code" => "03-165",
                "password" => "03-165",
                "email" => "alan.pacho.26@gmail.com",
                "address" => "c/ Otero las cuadras",
                "mobile_number" => "75949190",
                "phone_number" => "",
                "college_affiliation_date" => "2021-04-19"
            ],
            [
                "first_name" => "Johnny",
                "last_name" => "Bascopé  Gutiérrez",
                "ci" => "4466834 Cbba",
                "registration_code" => "03-166",
                "password" => "03-166",
                "email" => "jbascope@ctb.com.bo",
                "address" => "c/ Los laureles Villa Moscu",
                "mobile_number" => "70766985",
                "phone_number" => "",
                "college_affiliation_date" => "2021-05-18"
            ],
            [
                "first_name" => "Rider",
                "last_name" => "Sanchez  Acosta",
                "ci" => "8700149 Cbba",
                "registration_code" => "03-168",
                "password" => "03-168",
                "email" => "sanchezrider76@gmail.com",
                "address" => "Ucuchi-Sacaba",
                "mobile_number" => "73692860",
                "phone_number" => "",
                "college_affiliation_date" => "2021-07-01"
            ],
            [
                "first_name" => "Alvaro",
                "last_name" => "Hinojosa  Mamani",
                "ci" => "9345929 Cbba",
                "registration_code" => "03-169",
                "password" => "03-169",
                "email" => "ahinojosa@ctb.com.bo",
                "address" => "c/Santa Cruz- Sacaba",
                "mobile_number" => "77928972",
                "phone_number" => "",
                "college_affiliation_date" => "2021-07-28"
            ],
            [
                "first_name" => "Eliseo",
                "last_name" => "Solíz  Lopez",
                "ci" => "6400641 Cbba",
                "registration_code" => "03-172",
                "password" => "03-172",
                "email" => "solizeliseo2@gmail.com",
                "address" => "Villa Tunari- Sacaba",
                "mobile_number" => "73774089",
                "phone_number" => "",
                "college_affiliation_date" => "2021-12-02"
            ],
            [
                "first_name" => "Freddy  Luis",
                "last_name" => "Choque  Cori",
                "ci" => "8683338 Cbba",
                "registration_code" => "03-176",
                "password" => "03-176",
                "email" => "freddyluis@outlook.es",
                "address" => "Molle Molle-Sacaba",
                "mobile_number" => "77962888",
                "phone_number" => "",
                "college_affiliation_date" => "2022-01-25"
            ],
            [
                "first_name" => "Alvaro",
                "last_name" => "Vallejos  Cardona",
                "ci" => "8007371 Cbba",
                "registration_code" => "03-177",
                "password" => "03-177",
                "email" => "vallejoslord.23@gmail.com",
                "address" => "Valle Sajta",
                "mobile_number" => "78320444",
                "phone_number" => "",
                "college_affiliation_date" => "2022-02-07"
            ],
            [
                "first_name" => "Ilmer",
                "last_name" => "Méndez  Lopez",
                "ci" => "7901326 Cbba",
                "registration_code" => "03-178",
                "password" => "03-178",
                "email" => "mendezshaka@gmail.com",
                "address" => "C/ Litoral - Sacaba",
                "mobile_number" => "67478693",
                "phone_number" => "",
                "college_affiliation_date" => "2022-02-15"
            ],
            [
                "first_name" => "Raúl",
                "last_name" => "Gómez  Claros",
                "ci" => "7994457 Cbba",
                "registration_code" => "03-179",
                "password" => "03-179",
                "email" => "rgomez@ctb.com.bo",
                "address" => "B. Palmeras - Shinahota",
                "mobile_number" => "71010654",
                "phone_number" => "",
                "college_affiliation_date" => "2022-03-28"
            ],
            [
                "first_name" => "Roman",
                "last_name" => "Otalora  Colque",
                "ci" => "8701645 Cbba",
                "registration_code" => "03-182",
                "password" => "03-182",
                "email" => "rotalora@ctb.com.bo",
                "address" => "Av. Santa Cruz- Quillacollo",
                "mobile_number" => "68570605",
                "phone_number" => "",
                "college_affiliation_date" => "2022-03-30"
            ],
            [
                "first_name" => "Sergio",
                "last_name" => "Guzman  Ledezma",
                "ci" => "9352933 Cbba",
                "registration_code" => "03-183",
                "password" => "03-183",
                "email" => "ser.rko.viper@gmail.es",
                "address" => "Esmeralda norte-Sacaba",
                "mobile_number" => "60367151",
                "phone_number" => "",
                "college_affiliation_date" => "2022-03-30"
            ],
            [
                "first_name" => "Richard  Ulises",
                "last_name" => "Guzman  Ledezma",
                "ci" => "9420935 Cbba.",
                "registration_code" => "03-184",
                "password" => "03-184",
                "email" => "rguzman@ctb.com.bo",
                "address" => "Av. Circunvalación - S/N - Z/Amancayas",
                "mobile_number" => "69454492",
                "phone_number" => "",
                "college_affiliation_date" => "2022-03-30"
            ],
            [
                "first_name" => "Edwin",
                "last_name" => "Garcia  Aguilar",
                "ci" => "7917942 Cbba.",
                "registration_code" => "03-185",
                "password" => "03-185",
                "email" => "egarcia@ctb.com.bo",
                "address" => "C/Comercio - Shinahota - Cbba.",
                "mobile_number" => "63956636",
                "phone_number" => "",
                "college_affiliation_date" => "2022-04-19"
            ],
            [
                "first_name" => "Limbert",
                "last_name" => "Zurita  Rodriguez",
                "ci" => "8714958 Cbba.",
                "registration_code" => "03-186",
                "password" => "03-186",
                "email" => "lzurita@ctb.com.bo",
                "address" => "Z/Convento - Trarata",
                "mobile_number" => "67414945",
                "phone_number" => "",
                "college_affiliation_date" => "2022-04-27"
            ],
            [
                "first_name" => "Miguel  Angel",
                "last_name" => "Panozo  Rocha",
                "ci" => "7948332 Cbba.",
                "registration_code" => "03-187",
                "password" => "03-187",
                "email" => "mpanozo@ctb.com.bo",
                "address" => "C/Inominada S/N Z/Pampa San Miguel Cbba.",
                "mobile_number" => "76460366",
                "phone_number" => "",
                "college_affiliation_date" => "2022-04-27"
            ],
            [
                "first_name" => "Vidal",
                "last_name" => "Janco  Alcazar",
                "ci" => "5904034 Cbba.",
                "registration_code" => "03-188",
                "password" => "03-188",
                "email" => "vjanco@ctb.com.bo",
                "address" => "El Paso - Quillacollo",
                "mobile_number" => "69434796",
                "phone_number" => "",
                "college_affiliation_date" => "2022-04-29"
            ],
            [
                "first_name" => "Ruben",
                "last_name" => "Meneces  Siles",
                "ci" => "9317626 Cbba.",
                "registration_code" => "03-189",
                "password" => "03-189",
                "email" => "rmeneces@ctb.com.bo",
                "address" => "Av. V. Paz S/N Cerro San Miguel Cbba",
                "mobile_number" => "79386465",
                "phone_number" => "",
                "college_affiliation_date" => "2022-05-17"
            ],
            [
                "first_name" => "Yumar",
                "last_name" => "Amaru  Perez",
                "ci" => "8683831 Cbba.",
                "registration_code" => "03-190",
                "password" => "03-190",
                "email" => "yumararies2012@gmail.com",
                "address" => "Catachilla Baja - Sacaba",
                "mobile_number" => "73838709",
                "phone_number" => "",
                "college_affiliation_date" => "2022-06-17"
            ],
            [
                "first_name" => "Nelson  Lucio",
                "last_name" => "Quispe  Nacho",
                "ci" => "4761998 LP.",
                "registration_code" => "03-191",
                "password" => "03-191",
                "email" => "nquispe@ctb.com.bo",
                "address" => "Av. Antofagasta S/N - Quillacollo",
                "mobile_number" => "72790731",
                "phone_number" => "",
                "college_affiliation_date" => "2022-06-23"
            ],
            [
                "first_name" => "Jhoselin",
                "last_name" => "Alejandro  Perez",
                "ci" => "12520940 Cbba.",
                "registration_code" => "03-192",
                "password" => "03-192",
                "email" => "jalejandro@ctb.com.bo",
                "address" => "Z/Villa Obrajes - Sacaba - Cbba.",
                "mobile_number" => "63529162",
                "phone_number" => "",
                "college_affiliation_date" => "2022-07-19"
            ],
            [
                "first_name" => "Juan",
                "last_name" => "Ibarra  Heredia",
                "ci" => "8049208 Cbba.",
                "registration_code" => "03-193",
                "password" => "03-193",
                "email" => "jibarra@ctb.com.bo",
                "address" => "Av. Villazon Km. 10 Huayllani - Sacaba",
                "mobile_number" => "70772153",
                "phone_number" => "",
                "college_affiliation_date" => "2022-08-04"
            ],
            [
                "first_name" => "Juan  Carlos",
                "last_name" => "Puma  Taca",
                "ci" => "8517143 Ptsi",
                "registration_code" => "03-194",
                "password" => "03-194",
                "email" => "jpuma@ctb.com.bo",
                "address" => "Tiutimayu",
                "mobile_number" => "74367684",
                "phone_number" => "",
                "college_affiliation_date" => "2022-10-04"
            ],
            [
                "first_name" => "Marcial",
                "last_name" => "Cruz  Lopez",
                "ci" => "7996594 Cbba.",
                "registration_code" => "03-195",
                "password" => "03-195",
                "email" => "mcruz@ctb.com.bo",
                "address" => "C/Ecologica S/N Z/Villa Obrajes - Sacaba",
                "mobile_number" => "72711528",
                "phone_number" => "",
                "college_affiliation_date" => "2022-10-14"
            ],
            [
                "first_name" => "Wilson",
                "last_name" => "Martinez  Caceres",
                "ci" => "9413496 Cbba.",
                "registration_code" => "03-196",
                "password" => "03-196",
                "email" => "wmartinez@ctb.com.bo",
                "address" => "C/Colcha N° 4750 - Villa Pagador - Z/Sud",
                "mobile_number" => "68591170",
                "phone_number" => "",
                "college_affiliation_date" => "2022-10-24"
            ],
            [
                "first_name" => "Bauster",
                "last_name" => "Vargas  Canaviri",
                "ci" => "5933464 Cbba.",
                "registration_code" => "03-197",
                "password" => "03-197",
                "email" => "bausther1vargas@gmail.com",
                "address" => "Barrio 1° de Mayo - Zona 4 S/N",
                "mobile_number" => "72794932",
                "phone_number" => "",
                "college_affiliation_date" => "2022-10-31"
            ],
            [
                "first_name" => "Estefany  E.",
                "last_name" => "Herrera  Rodriguez",
                "ci" => "6480492 LP.",
                "registration_code" => "03-198",
                "password" => "03-198",
                "email" => "eherrera@ctb.com.bo",
                "address" => "C/Mariano Mendez - N° 2128 Z/Norte - Cbba.",
                "mobile_number" => "64923127",
                "phone_number" => "",
                "college_affiliation_date" => "2022-11-03"
            ],
            [
                "first_name" => "Rodrigo",
                "last_name" => "Panozo  Condori",
                "ci" => "6506725 Cbba",
                "registration_code" => "03-199",
                "password" => "03-199",
                "email" => "roka210988@gmail.com",
                "address" => "Av. Circunvalacíon S/N Z/Norte - Cbba.",
                "mobile_number" => "78370628",
                "phone_number" => "",
                "college_affiliation_date" => "2022-12-01"
            ],
            [
                "first_name" => "Maria",
                "last_name" => "Macias  Claros",
                "ci" => "9342993 Cbba.",
                "registration_code" => "03-200",
                "password" => "03-200",
                "email" => "mmacias@ctb.com.bo",
                "address" => "C/Pueblo de Belen S/N - Z/Villa Isrrael - Cbba.",
                "mobile_number" => "72241569",
                "phone_number" => "",
                "college_affiliation_date" => "2022-12-02"
            ],
            [
                "first_name" => "Jose  Antonio",
                "last_name" => "Crespo  Lazarte",
                "ci" => "8834318 cbba.",
                "registration_code" => "03-201",
                "password" => "03-201",
                "email" => "crespojosea7@gmail.com",
                "address" => "C/Incachaca - Sacaba",
                "mobile_number" => "75493704",
                "phone_number" => "",
                "college_affiliation_date" => "2022-12-14"
            ],
            [
                "first_name" => "Clemente",
                "last_name" => "Soto  Condori",
                "ci" => "5154173 Cbba.",
                "registration_code" => "03-202",
                "password" => "03-202",
                "email" => "csoto@ctb.com.bo",
                "address" => "C/Cruz del Sur - B/Libertador - Cbba.",
                "mobile_number" => "78329326",
                "phone_number" => "",
                "college_affiliation_date" => "2022-12-19"
            ],
            [
                "first_name" => "Jorge",
                "last_name" => "Aguilar  Triveño",
                "ci" => "12556110 Cbba",
                "registration_code" => "03-203",
                "password" => "03-203",
                "email" => "jaguilar@ctb.com.bo",
                "address" => "Mayu Molino - Sacaba",
                "mobile_number" => "76486426",
                "phone_number" => "",
                "college_affiliation_date" => "2023-01-10"
            ],
            [
                "first_name" => "Alvaro",
                "last_name" => "Nogales  Montaño",
                "ci" => "8024659 CBBA",
                "registration_code" => "03-204",
                "password" => "03-204",
                "email" => "anogales@ctb.com.bo",
                "address" => "Tacopoca - Sacaba - Cbba.",
                "mobile_number" => "76405053",
                "phone_number" => "",
                "college_affiliation_date" => "2023-01-17"
            ],
            [
                "first_name" => "Israel",
                "last_name" => "Breton  Laime",
                "ci" => "7960959 CBBA",
                "registration_code" => "03-205",
                "password" => "03-205",
                "email" => "ibreton@ctb.com.bo",
                "address" => "Z/Norte Temporal - Cbba.",
                "mobile_number" => "68507606",
                "phone_number" => "",
                "college_affiliation_date" => "2023-01-26"
            ],
            [
                "first_name" => "Jose  Luis",
                "last_name" => "Vargas  Vargas",
                "ci" => "7929244 Cbba.",
                "registration_code" => "03-206",
                "password" => "03-206",
                "email" => "jvargas@ctb.com.bo",
                "address" => "Z/El Morro - Sacaba -Cbba.",
                "mobile_number" => "71434565",
                "phone_number" => "",
                "college_affiliation_date" => "2023-01-31"
            ],
            [
                "first_name" => "Richard  Wilber",
                "last_name" => "Fernandez  Cadima",
                "ci" => "6501848 Cbba",
                "registration_code" => "03-207",
                "password" => "03-207",
                "email" => "rfernandez@ctb.com.bo",
                "address" => "Z/Tuti Mayu Km25 - Sacaba - Cbba.",
                "mobile_number" => "68471154",
                "phone_number" => "",
                "college_affiliation_date" => "2023-02-03"
            ],
            [
                "first_name" => "Juan  Jose",
                "last_name" => "Paredes  Caceres",
                "ci" => "9396142 Cbba.",
                "registration_code" => "03-208",
                "password" => "03-208",
                "email" => "jparedes@ctb.com.bo",
                "address" => "C/Ingavi - Sacaba",
                "mobile_number" => "72218264",
                "phone_number" => "",
                "college_affiliation_date" => "2023-03-03"
            ],
            [
                "first_name" => "Wilfredo",
                "last_name" => "Vargas  Tola",
                "ci" => "9417683 Cbba.",
                "registration_code" => "03-209",
                "password" => "03-209",
                "email" => "wvargas@ctb.com.bo",
                "address" => "Chimore - Cbba.",
                "mobile_number" => "67416537",
                "phone_number" => "",
                "college_affiliation_date" => "2023-04-01"
            ],
            [
                "first_name" => "Luis  Beltran",
                "last_name" => "Ramirez  Echeverria",
                "ci" => "7353532 Cbba.",
                "registration_code" => "03-210",
                "password" => "03-210",
                "email" => "lramirez@ctb.com.bo",
                "address" => "Villa Choro - Tapacari - Cbba.",
                "mobile_number" => "68288401",
                "phone_number" => "",
                "college_affiliation_date" => "2023-04-12"
            ],
            [
                "first_name" => "Luis  Rodrigo",
                "last_name" => "Zapata  Zurita",
                "ci" => "8669893 Cbba.",
                "registration_code" => "03-211",
                "password" => "03-211",
                "email" => "lzapata@ctb.com.bo",
                "address" => "Villa Obrajes -Sacaba - Cbba.",
                "mobile_number" => "-",
                "phone_number" => "",
                "college_affiliation_date" => "2023-05-18"
            ],
            [
                "first_name" => "Omar",
                "last_name" => "Totora  Veliz",
                "ci" => "5902473 Cbba.",
                "registration_code" => "03-212",
                "password" => "03-212",
                "email" => "ototora@ctb.com.bo",
                "address" => "Z/Villa pagador -Av. Humberto Asiru",
                "mobile_number" => "61590311",
                "phone_number" => "",
                "college_affiliation_date" => "2023-05-11"
            ],
            [
                "first_name" => "Julia  Karina",
                "last_name" => "Soto  Vidal",
                "ci" => "9452860 Cbba.",
                "registration_code" => "03-213",
                "password" => "03-213",
                "email" => "jsoto@ctb.com.bo",
                "address" => "Av. Centenario N° 84 - Z/Taquiña - Cbba.",
                "mobile_number" => "61610410",
                "phone_number" => "",
                "college_affiliation_date" => "2023-06-23"
            ],
            [
                "first_name" => "Deymar",
                "last_name" => "Virgo  Peñaranda",
                "ci" => "10339445 CH.",
                "registration_code" => "03-214",
                "password" => "03-214",
                "email" => "dvirgo@ctb.com.bo",
                "address" => "Z/Temporal - Cbba.",
                "mobile_number" => "73428297",
                "phone_number" => "",
                "college_affiliation_date" => "2023-07-28"
            ],
            [
                "first_name" => "Saul  Santos",
                "last_name" => "Calvi  Aguilar",
                "ci" => "7904966 Cbba.",
                "registration_code" => "03-215",
                "password" => "03-215",
                "email" => "saulsantos2296@gmail.com",
                "address" => "C/Victor Paz Estensoro N° 1145 Z/Cerro San Miguel - Cbba.",
                "mobile_number" => "65777576",
                "phone_number" => "",
                "college_affiliation_date" => "2023-07-27"
            ],
            [
                "first_name" => "Brian  Edson",
                "last_name" => "Verduguez  Andia",
                "ci" => "9438203 Cbba.",
                "registration_code" => "03-216",
                "password" => "03-216",
                "email" => "bverduguez@ctb.com.bo",
                "address" => "Parada 4 1/2 - Z/Maica Sud - Cbba.",
                "mobile_number" => "78329347",
                "phone_number" => "",
                "college_affiliation_date" => "2023-08-01"
            ],
            [
                "first_name" => "Eva",
                "last_name" => "Inturias  Ambrocio",
                "ci" => "9480265 Cbba.",
                "registration_code" => "03-217",
                "password" => "03-217",
                "email" => "inturiaseva95@gmail.com",
                "address" => "",
                "mobile_number" => "76992455",
                "phone_number" => "",
                "college_affiliation_date" => "2023-08-08"
            ],
            [
                "first_name" => "Jhery  Pedro",
                "last_name" => "Aguilar  Coria",
                "ci" => "9317083 Cbba.",
                "registration_code" => "03-218",
                "password" => "03-218",
                "email" => "jheryaguilar43@gmail.com",
                "address" => "",
                "mobile_number" => "78328200",
                "phone_number" => "",
                "college_affiliation_date" => "2023-08-15"
            ],
            [
                "first_name" => "Jose  Jherman",
                "last_name" => "Alarcon  Mamani",
                "ci" => "9315300 Cbba.",
                "registration_code" => "03-219",
                "password" => "03-219",
                "email" => "jhermann.ing@gmail.com",
                "address" => "",
                "mobile_number" => "60362232",
                "phone_number" => "",
                "college_affiliation_date" => "2023-08-15"
            ],
            [
                "first_name" => "Juan  Cesar",
                "last_name" => "Mamani  Escalera",
                "ci" => "9534101 Cbba.",
                "registration_code" => "03-220",
                "password" => "03-220",
                "email" => "jcmamani@ctb.com.bo",
                "address" => "",
                "mobile_number" => "74937791",
                "phone_number" => "",
                "college_affiliation_date" => "2023-08-23"
            ],
            [
                "first_name" => "Carlos",
                "last_name" => "Torrico  Vallejos",
                "ci" => "6522086 Cbba",
                "registration_code" => "03-221",
                "password" => "03-221",
                "email" => "ctorrico@ctb.com.bo",
                "address" => "",
                "mobile_number" => "71430048",
                "phone_number" => "",
                "college_affiliation_date" => "2023-08-25"
            ],
            [
                "first_name" => "Elda",
                "last_name" => "Calle  Sanchez",
                "ci" => "9340302 QR",
                "registration_code" => "03-222",
                "password" => "03-222",
                "email" => "ecalle@ctb.com.bo",
                "address" => "",
                "mobile_number" => "69475319",
                "phone_number" => "",
                "college_affiliation_date" => "2023-08-28"
            ],
            [
                "first_name" => "Ivo  Alejandro",
                "last_name" => "Viscarra  Arze",
                "ci" => "6434441 QR",
                "registration_code" => "03-223",
                "password" => "03-223",
                "email" => "iviscarra@ctb.com.bo",
                "address" => "",
                "mobile_number" => "69433436",
                "phone_number" => "",
                "college_affiliation_date" => "2023-08-28"
            ],
            [
                "first_name" => "Bertha",
                "last_name" => "Ordoñez  Terrazas",
                "ci" => "8024855 Cbba.",
                "registration_code" => "03-224",
                "password" => "03-224",
                "email" => "bordonez@ctb.com.bo",
                "address" => "",
                "mobile_number" => "71781589",
                "phone_number" => "",
                "college_affiliation_date" => "2023-10-10"
            ],
            [
                "first_name" => "Orlando",
                "last_name" => "Reyes  Flores",
                "ci" => "7938825Cbba.",
                "registration_code" => "03-225",
                "password" => "03-225",
                "email" => "orland0712king@gmail.com",
                "address" => "",
                "mobile_number" => "76995400",
                "phone_number" => "",
                "college_affiliation_date" => "2023-10-24"
            ],
            [
                "first_name" => "Ruth",
                "last_name" => "Peredo  Vargas",
                "ci" => "13483490 Cbba.",
                "registration_code" => "03-226",
                "password" => "03-226",
                "email" => "rperedo@ctb.com.bo",
                "address" => "",
                "mobile_number" => "69535754",
                "phone_number" => "",
                "college_affiliation_date" => "2023-10-24"
            ],
            [
                "first_name" => "Patricia  Monica",
                "last_name" => "Condes  Cadima",
                "ci" => "4999547 L.P.",
                "registration_code" => "03-227",
                "password" => "03-227",
                "email" => "pcondes@ctb.com.bo",
                "address" => "",
                "mobile_number" => "76709544",
                "phone_number" => "",
                "college_affiliation_date" => "2023-10-26"
            ],
            [
                "first_name" => "Carlos",
                "last_name" => "Mendieta  Arnez",
                "ci" => "7934773 Cbba",
                "registration_code" => "03-228",
                "password" => "03-228",
                "email" => "cmendieta@ctb.com.bo",
                "address" => "",
                "mobile_number" => "67612699",
                "phone_number" => "",
                "college_affiliation_date" => "2023-11-13"
            ],
            [
                "first_name" => "Diego  Yeager",
                "last_name" => "Camacho  Chiri",
                "ci" => "8032756 Cbba.",
                "registration_code" => "03-229",
                "password" => "03-229",
                "email" => "dcamacho@ctb.com.bo",
                "address" => "",
                "mobile_number" => "60388128",
                "phone_number" => "",
                "college_affiliation_date" => "2023-11-21"
            ],
            [
                "first_name" => "Richard",
                "last_name" => "Zeballos  Almanza",
                "ci" => "8826608 cbba.",
                "registration_code" => "03-230",
                "password" => "03-230",
                "email" => "rzeballos@ctb.com.bo",
                "address" => "",
                "mobile_number" => "63895601",
                "phone_number" => "",
                "college_affiliation_date" => "2023-12-19"
            ],
            [
                "first_name" => "Mario",
                "last_name" => "Chavarria  Flores",
                "ci" => "7511088 Ch.",
                "registration_code" => "03-231",
                "password" => "03-231",
                "email" => "mchavarria@ctb.com.bo",
                "address" => "",
                "mobile_number" => "73419886",
                "phone_number" => "",
                "college_affiliation_date" => "2024-01-17"
            ],
            [
                "first_name" => "Rene",
                "last_name" => "Charquetuna  Oporto",
                "ci" => "10565728 Pt.",
                "registration_code" => "03-232",
                "password" => "03-232",
                "email" => "rcharquetuna@ctb.com.bo",
                "address" => "",
                "mobile_number" => "74135391",
                "phone_number" => "",
                "college_affiliation_date" => "2024-01-22"
            ],
            [
                "first_name" => "Alvaro",
                "last_name" => "Amurrio  Alcocer",
                "ci" => "8016563 Cbba.",
                "registration_code" => "03-233",
                "password" => "03-233",
                "email" => "aamurrio@ctb.com.bo",
                "address" => "",
                "mobile_number" => "75915272",
                "phone_number" => "",
                "college_affiliation_date" => "2024-01-26"
            ],
            [
                "first_name" => "Guido",
                "last_name" => "Zalles  Choque",
                "ci" => "6856343 L.P.",
                "registration_code" => "03-234",
                "password" => "03-234",
                "email" => "gzalles@ctb.com.bo",
                "address" => "",
                "mobile_number" => "60593972",
                "phone_number" => "",
                "college_affiliation_date" => "2024-02-16"
            ],
            [
                "first_name" => "Samuel",
                "last_name" => "Pacheco  Veizaga",
                "ci" => "12490073 Cbba.",
                "registration_code" => "03-235",
                "password" => "03-235",
                "email" => "spacheco@ctb.com.bo",
                "address" => "",
                "mobile_number" => "72296310",
                "phone_number" => "",
                "college_affiliation_date" => "2024-04-03"
            ],
            [
                "first_name" => "Jose  Luis",
                "last_name" => "Cornejo  Camacho",
                "ci" => "5931098 QR",
                "registration_code" => "03-236",
                "password" => "03-236",
                "email" => "jcornejo@ctb.com.bo",
                "address" => "",
                "mobile_number" => "68181662",
                "phone_number" => "",
                "college_affiliation_date" => "2024-06-12"
            ],
            [
                "first_name" => "Nelson",
                "last_name" => "Siles  Padilla",
                "ci" => "8023324 Cbba.",
                "registration_code" => "03-237",
                "password" => "03-237",
                "email" => "nsiles@ctb.com.bo",
                "address" => "",
                "mobile_number" => "79735885",
                "phone_number" => "",
                "college_affiliation_date" => "2024-07-02"
            ],
            [
                "first_name" => "Ruben",
                "last_name" => "Condori  Mejia",
                "ci" => "6684249 Pt.",
                "registration_code" => "03-238",
                "password" => "03-238",
                "email" => "rcondori@ctb.com.bo",
                "address" => "",
                "mobile_number" => "67233075",
                "phone_number" => "",
                "college_affiliation_date" => "2024-07-25"
            ],
            [
                "first_name" => "Jose  Luis",
                "last_name" => "Cruz  Caraballo",
                "ci" => "7883346 Cbba.",
                "registration_code" => "03-239",
                "password" => "03-239",
                "email" => "jcruz@ctb.com.bo",
                "address" => "",
                "mobile_number" => "",
                "phone_number" => "",
                "college_affiliation_date" => "2024-08-17"
            ],
            [
                "first_name" => "Fabian",
                "last_name" => "Achaya  Ajomado",
                "ci" => "8560838 Pt.",
                "registration_code" => "03-240",
                "password" => "03-240",
                "email" => "fachaya@ctb.com.bo",
                "address" => "",
                "mobile_number" => "",
                "phone_number" => "",
                "college_affiliation_date" => "2024-09-26"
            ],
            [
                "first_name" => "Jimmy",
                "last_name" => "Mercado  Mamani",
                "ci" => "5911457 Cbba.",
                "registration_code" => "03-241",
                "password" => "03-241",
                "email" => "jmercado@ctb.com.bo",
                "address" => "",
                "mobile_number" => "73798038",
                "phone_number" => "",
                "college_affiliation_date" => "2024-10-02"
            ],
            [
                "first_name" => "Jocman",
                "last_name" => "Flores  Ricaldes",
                "ci" => "8739223 Cbba",
                "registration_code" => "03-242",
                "password" => "03-242",
                "email" => "jflores@ctb.com.bo",
                "address" => "",
                "mobile_number" => "",
                "phone_number" => "",
                "college_affiliation_date" => "2024-10-14"
            ],
            [
                "first_name" => "Jose  E.",
                "last_name" => "Huanca  Gutierrez",
                "ci" => "8818925 Cbba",
                "registration_code" => "03-243",
                "password" => "03-243",
                "email" => "jhuanca@ctb.com.bo",
                "address" => "",
                "mobile_number" => "71005773",
                "phone_number" => "",
                "college_affiliation_date" => "2024-12-05"
            ],
            [
                "first_name" => "Jorge  Hans",
                "last_name" => "Aquino  Yucra",
                "ci" => "8407978 L.P.",
                "registration_code" => "03-244",
                "password" => "03-244",
                "email" => "jaquino@ctb.com.bo",
                "address" => "",
                "mobile_number" => "75867117",
                "phone_number" => "",
                "college_affiliation_date" => "2025-01-29"
            ],
            [
                "first_name" => "Jhonatan",
                "last_name" => "Mirabal  Rodrigo",
                "ci" => "8670685 Cbba.",
                "registration_code" => "03-245",
                "password" => "03-245",
                "email" => "jmirabal@ctb.com.bo",
                "address" => "",
                "mobile_number" => "67454225",
                "phone_number" => "",
                "college_affiliation_date" => "2025-03-10"
            ],
            [
                "first_name" => "Christian Mauricio",
                "last_name" => "Aldana Martinez",
                "ci" => "7485587 CHQ.",
                "registration_code" => "ene-70",
                "password" => "ene-70",
                "email" => "caldana@ctb.com.bo",
                "address" => "",
                "mobile_number" => "",
                "phone_number" => "",
                "college_affiliation_date" => "2023-12-06"
            ]
        ];

        foreach ($users as $user) {
            if (isset($user['college_affiliation_date'])) {
                $user['college_affiliation_date'] = $user['college_affiliation_date'] === 'NULL' ? null : $user['college_affiliation_date'];
            }

            User::create($user);
        }
    }
}
